project:
  type: website
  output-dir: docs

website:
  title: "Andrew Dean's Machine Learning Blog"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd
      - icon: github
        href: https://github.com/andrewdean1

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true





